### ISSUE TITLE
Duplicated postalCode in FetchShippingCostAndMethod model

### ISSUE THREAD

**Issue by zaporylie** [vippsas/vipps-ecom-api#52]
FetchShippingCostAndMethod has two identical properties: postCode and postalCode. According to docs former is required and latter is optional. Both must be four digits but example documentation shows 3 digit number.

See https://github.com/vippsas/vipps-ecom-api/blob/9ac4024f9f2fd1b34df39c708c74a382cbc2fd3f/docs/swagger.yaml#L1458-L1469

1. Is the postCode preferred over postalCode? What is latter used for?
2. Can you update example value from 3 digit to 4 digit one so that it matches validation criteria?

**Comment by cloveras** [comment]
Hi, and thanks for reporting this! 

We are looking into it, sorry for not updating here earlier. This is, of course, embarrassing. A string with a regex only allowing four digits? It may be due to having moved Swagger files around, and getting some auto-generation "help" without noticing. Hopefully we will clean this up quickly.

Christian, Vipps

**Comment by tht13** [comment]
The preference is postCode, but either are accepted, and in this version of the API we unfortunately cannot remove one or the other as this may break compatibility for merchants. However we will improve the examples.
